In [0]:
import numpy as np

In [0]:
C = np.array([[1,-2,0],[-2,5,0],[0,0,2]])

In [0]:
C

array([[ 1, -2,  0],
       [-2,  5,  0],
       [ 0,  0,  2]])

In [0]:
# Tính ma trận hiệp phương sai (covariance matrix)

In [0]:
cov = np.cov(C)
cov

array([[ 2.33333333, -5.5       ,  0.33333333],
       [-5.5       , 13.        , -1.        ],
       [ 0.33333333, -1.        ,  1.33333333]])

In [0]:
# Tính Eigenvectors and corresponding Eigenvalues

In [0]:
# Let A be a square matrix, ν a vector and λ a scalar that satisfies Aν = λν, then λ is called 
# eigenvalue associated with eigenvector ν of A.

In [0]:
# Với A là một ma trận vuông , v là một vector và λ là một vector vô hướng thỏa mã Av = λv, khi đó
# λ được gọi là giá trị riêng với vector riêng của A
# Thõa mãn det(A - λl) = 0

In [0]:
# Ta có det(C - λl) = 0 với l là một ma trận đơn vị

In [0]:
'''
                    [[1,   0,    0],
          C   - λ*   [0,   1,    0],
                     [0,   0,    1]] '''

In [0]:
'''
       [[ 1, -2,  0],       [[λ,   0,    0],
        [-2,  5,  0],  -     [0,   λ,    0],
        [ 0,  0,  2]]        [0,   0,    λ]] '''

In [0]:
'''
       [[ 1 - λ ,-2       ,  0    ]
        [-2     , 5  -λ   ,  0    ]
        [ 0     , 0       ,  2  -λ]]   '''

In [0]:
''' det([[ 1 - λ ,-2       ,  0    ]
        [-2     , 5  -λ   ,  0    ]
        [ 0     , 0       ,  2  -λ]])   = 0 '''

In [0]:
''' det(C) = 0 => (a11*a22*a33 + a12*a23*a31 + a13*a21*a32 - a13*a22*a31 -a12*a21*a33 - a11*a23*a32) = 0
                => ((1-λ)*(5-λ)*(2-λ) + (-2*0*0) + (0) - (0) - (-2*-2*(2-λ)) - (0) = 0 '''

In [0]:

# => λ1= 0.17157288
#    λ2= 5.82842712
#    λ3= 2.
# => Đây là giá trị eigenvalue

In [0]:
# Tính giá trị eigenvector => A*

In [0]:
# Với λ1= 0.17157288:
# (A - λl)v1 = 0 =>  [ 1 - λl,   -2,  0],    [[x],         
#                   [-2,    5 - λl,  0], *  [y],  = 0 =>  
#                   [ 0,    0 ,  2 - λl]]    [z]]          
# => v1 = (-0.92387953  0.38268343  0.)

In [0]:
# tương tự với v2 và v3 

Tính toán lại bằng hàm

In [0]:
from numpy import linalg as LA

In [0]:
w, a = LA.eig(C)

In [0]:
print("eigenvalue là", w )

eigenvalue là [0.17157288 5.82842712 2.        ]


In [3]:
0.17157288 + 5.82842712

6.0

In [0]:
print("eigenvector là")
for i in a:
  print(i)

eigenvector là
[-0.92387953  0.38268343  0.        ]
[-0.38268343 -0.92387953  0.        ]
[0. 0. 1.]


### Tính pricipal component Y1, Y2, Y3

In [0]:
# Ta có Y1 = v1*X = -0.92387953*X1 + 0.38268343*X2 + 0*X3   
# Ta có Y2 = v2*X = -0.38268343*X1 -0.92387953*X2  0.*X3
# Ta có Y3 = v3*X = 0.*X1 + 0.*X2 + 1.*X3

In [0]:
# Ta có tổng phương sai = Tổng trị riêng = λl + λ2 + λ3 = 8 => 